EAPI=7

inherit go-module

EGO_PN="github.com/mbaraa/eloi"
DESCRIPTION="Eix with extra steps"
HOMEPAGE="https://github.com/mbaraa/eloi"
SRC_URI="https://github.com/mbaraa/eloi/archive/v${PV}.tar.gz -> ${P}.tar.gz
			${EGO_SUM_SRC_URI}"

BDEPEND=">=dev-lang/go-1.19"

go-module_set_globals

# generated by dev-go/golicense
LICENSE="Apache-2.0 BSD MIT GPL-3"
SLOT="0"
KEYWORDS=""
IUSE=""

src_compile() {
	go get
	go build -o eloi\
		-ldflags="-w -s"
}

src_install() {
	dobin eloi
	dodoc README.md
}
